insert into musicalservice.album  values (1, 'Sesame Street Presents Follow That Bird', 'single', '204.237.73.79');
insert into musicalservice.album  values (2, 'Strange Cargo', 'soundtrack', null);
insert into musicalservice.album  values (3, 'Aragami', 'soundtrack', null);
insert into musicalservice.album  values (4, 'Brick Mansions', 'live', '129.110.210.56');
insert into musicalservice.album  values (5, 'One in a Million: The Ron LeFlore Story', 'LP', '59.41.218.213');
insert into musicalservice.album  values (6, 'Daar', 'live', '200.178.58.119');
insert into musicalservice.album  values (7, 'Wilby Wonderful', 'LP', null);
insert into musicalservice.album  values (8, 'Born to Race', 'single', '105.30.159.44');
insert into musicalservice.album  values (9, 'The Divine Move', 'compilation', '91.192.230.75');
insert into musicalservice.album  values (10, 'Wrong Move, The (Falsche Bewegung)', 'EP', '145.193.213.82');
insert into musicalservice.album  values (11, 'Taipei Exchanges (Di 36 ge gu shi)', 'compilation', '81.164.75.192');
insert into musicalservice.album  values (12, 'I Want Someone to Eat Cheese With', 'live', '128.109.122.234');
insert into musicalservice.album  values (13, 'Everybody''s Fine', 'soundtrack', null);
insert into musicalservice.album  values (14, 'Dirty Love', 'compilation', '42.0.173.154');
insert into musicalservice.album  values (15, 'Elizabeth: The Golden Age', 'LP', '254.124.108.72');
insert into musicalservice.album  values (16, 'Hide-Out', 'soundtrack', '253.18.49.148');
insert into musicalservice.album  values (17, 'Welcome to Mooseport', 'EP', '183.155.229.130');
insert into musicalservice.album  values (18, 'Chicken with Plums (Poulet aux prunes)', 'soundtrack', '28.12.6.92');
insert into musicalservice.album  values (19, 'Oranges and Sunshine', 'EP', '36.33.160.198');
insert into musicalservice.album  values (20, 'Frankie and Alice', 'single', null);
