insert into musicalservice.artist_x_album values (1, 14, 'Japan release');
insert into musicalservice.artist_x_album values (2, 12, 'remastered');
insert into musicalservice.artist_x_album values (3, 4, 'original');
insert into musicalservice.artist_x_album values (4, 10, 'deluxe');
insert into musicalservice.artist_x_album values (5, 14, 'original');
insert into musicalservice.artist_x_album values (6, 4, 'Australia release');
insert into musicalservice.artist_x_album values (7, 13, 'original');
insert into musicalservice.artist_x_album values (8, 9, 'deluxe');
insert into musicalservice.artist_x_album values (9, 4, 'original');
insert into musicalservice.artist_x_album values (10, 1, 'original');
insert into musicalservice.artist_x_album values (11, 14, 'original');
insert into musicalservice.artist_x_album values (12, 13, 'deluxe');
insert into musicalservice.artist_x_album values (13, 8, 'remastered');
insert into musicalservice.artist_x_album values (14, 13, 'deluxe');
insert into musicalservice.artist_x_album values (15, 5, 'Australia release');
insert into musicalservice.artist_x_album values (16, 15, 'deluxe');
insert into musicalservice.artist_x_album values (17, 13, 'Australia release');
insert into musicalservice.artist_x_album values (18, 8, 'Australia release');
insert into musicalservice.artist_x_album values (19, 4, 'Japan release');
insert into musicalservice.artist_x_album values (20, 13, 'Australia release');
