insert into musicalservice.track values (1, 'R.I.P.D.', 'Irish Gaelic', '', true, null, true, 281);
insert into musicalservice.track values (2, 'Rain', 'Latvian', '', false, null, true, 256);
insert into musicalservice.track values (3, 'Mayerling', null, null, null, null, false, 397);
insert into musicalservice.track values (4, 'Voodoo Tiger', 'Dutch', '', true, null, false, 144);
insert into musicalservice.track values (5, 'Interstella 5555: The 5tory of the 5ecret 5tar 5ystem', 'Greek', '', false, null, false, 160);
insert into musicalservice.track values (6, 'Dead Man on Campus', 'Papiamento', '', false, null, true, 603);
insert into musicalservice.track values (7, 'Roadside Prophets', 'Telugu', '', false, null, true, 206);
insert into musicalservice.track values (8, 'Eclipse, The', 'Hungarian', '', true, null, true, 328);
insert into musicalservice.track values (9, 'Wholly Moses', 'Lithuanian', '', false, null, false, 665);
insert into musicalservice.track values (10, 'Bush Mama', 'Malagasy', '', true, null, false, 328);
insert into musicalservice.track values (11, 'Death Hunt', 'Yiddish', '', false, null, true, 154);
insert into musicalservice.track values (12, 'Restaurant', 'Maltese', '', false, null, false, 299);
insert into musicalservice.track values (13, 'Hindenburg, The', 'Catalan', '', true, null, false, 644);
insert into musicalservice.track values (14, 'Wild Geese II', 'Afrikaans', '', true, null, true, 517);
insert into musicalservice.track values (15, 'Dark Wind, The', 'German', '', false, null, true, 446);
insert into musicalservice.track values (16, 'Sanatorium', null, null, null, null, true, 144);
insert into musicalservice.track values (17, 'If Winter Comes', 'Hebrew', '', true, null, true, 579);
insert into musicalservice.track values (18, 'Under Siege', 'Norwegian', '', false, null, false, 369);
insert into musicalservice.track values (19, 'Marion Bridge', 'Assamese', '', true, null, false, 180);
insert into musicalservice.track values (20, 'Hugo Pool', 'Quechua', '', false, null, false, 112);
insert into musicalservice.track values (21, 'Funeral, The (Ososhiki)', 'Korean', '', false, null, true, 127);
insert into musicalservice.track values (22, 'Armored', 'Tetum', '', false, null, true, 612);
insert into musicalservice.track values (23, 'Pekko ja unissakävelijä', 'Latvian', '', false, null, true, 414);
insert into musicalservice.track values (24, 'Songcatcher', 'Kurdish', '', false, null, false, 512);
insert into musicalservice.track values (25, 'Passeio com Johnny Guitar', 'Guaraní', '', false, null, false, 195);
insert into musicalservice.track values (26, 'Industrial Symphony No. 1: The Dream of the Brokenhearted', 'Greek', '', false, null, false, 312);
insert into musicalservice.track values (27, 'Making the Grade', 'Ndebele', '', true, null, false, 507);
insert into musicalservice.track values (28, 'Wackness, The', 'Latvian', '', false, 'cmillanr', false, 286);
insert into musicalservice.track values (29, 'Rape of Europa, The', 'Guaraní', '', false, null, true, 380);
insert into musicalservice.track values (30, 'Saw', 'Sotho', '', false, null, false, 586);
insert into musicalservice.track values (31, 'Headless Woman, The (Mujer sin cabeza, La)', 'Hiri Motu', '', true, null, false, 80);
insert into musicalservice.track values (32, 'Wild Geese II', 'Macedonian', '', true, null, true, 367);
insert into musicalservice.track values (33, 'Don Quixote', 'Arabic', '', false, null, true, 401);
insert into musicalservice.track values (34, 'Killers', 'Oriya', '', true, null, true, 110);
insert into musicalservice.track values (35, 'Irreconcilable Differences', 'Arabic', '', true, null, true, 204);
insert into musicalservice.track values (36, 'Lad: A Dog', 'Romanian', '', true, null, true, 196);
insert into musicalservice.track values (37, 'Bad News Bears Go to Japan, The', 'Czech', '', false, null, false, 97);
insert into musicalservice.track values (38, 'Alien Nation: Millennium', 'Kyrgyz', '', true, null, false, 412);
insert into musicalservice.track values (39, 'Remember the Day', 'Aymara', '', false, null, true, 190);
insert into musicalservice.track values (40, '3-Iron (Bin-jip)', 'Amharic', '', true, null, false, 446);
